### ISSUE TITLE
Pre-render memory leak...

### ISSUE THREAD

**Issue by nhurde** [pawbyte/SDL_SurfaceEx#1]
Hello,

I've been hunting to discover why there is a memory leak via the prerender_circle function. 

It appears the surface is not being fully deleted via sdl_freesurface().

Will anyone be able to investigate the root cause of this issue?

If you are able to solve this I will donate a $20 gift gift card to you( Steam, NIntendo, Playstation, Xbox, etc).

**Comment by kphillisjr** [comment]
I cannot be certain unless I have more code to look at, but the issue from what I can tell in the headers is that there is incomplete bounds checking on the following functions:

- surface_render_horizontal_line_color
- surface_render_vertical_line_color
- surface_render_circle_color


The following lines of code should trigger unexpected behavior from what I currently see in the code.
```C

SDL_Surface* surf;
surf = SDL_CreateRGBSurfaceWithFormat(0, 64, 64, 32, SDL_PIXELFORMAT_RGBA32);
if (surf == NULL) {
	SDL_Log("SDL_CreateRGBSurfaceWithFormat() failed: %s", SDL_GetError());
	exit(1);
}

// Attempt to fill the surface using an oversized circle.
surface_render_circle_color( surf,  32, 32, 512, 0,0, 0, 255  );

// These are guaranteed to try and read an invalid memory location for a 64px by 64px surface.
surface_render_vertical_line_color( surf, 32,32, 66666666, 255, 255, 255, 255 );
surface_render_horizontal_line_color( surf, 32,32, 66666666, 255, 255, 255, 255 );

// attempt to draw circles on the 4 corners.
surface_render_circle_color( surf,  0, 0, 24, 255,255, 255, 255  );
surface_render_circle_color( surf,  0, 64, 24, 255,255, 255, 255  );
surface_render_circle_color( surf,  64, 0, 24, 255,255, 255, 255  );
surface_render_circle_color( surf,  64, 64, 24, 255,255, 255, 255  );
```

**Comment by nhurde** [comment]
Ah that is indeed a good point. I will add some bound checking.

**Comment by kphillisjr** [comment]
Here is two more bugs I noticed in the code...

- put_pixel32 needs negative bounds checking on x and y values.
- create_texture_from_surface - The surface in this function is not set to NULL for the calling function when destroy surface is set to true. Below is a short example of what this function is doing using strings, and also illustrates why the libSDL samples calling SDL_FreeSurface have the next line setting the variable to null.

```C++
#include <iostream>

void myPrintString(char* str, bool null_is_expected) {
    if (str == NULL) {
        std::cout << "String Is Null." << std::endl ;
        return;
    }
    if (null_is_expected) {
        std::cerr << "String is not Null. There is a problem." << std::endl ;
        return;
    }
    std::cout << str << std::endl << std::flush;
}
void myFreeString(char*a) {
    /* WARNING: This function does not set the pointer to null in the calling function.*/
    if (a != NULL) {
        free(a);
        /* This next line only effects this function. */
        a = NULL;
    }
}

void myFreeString2(char**a) {
    /* This function takes a pointer to a string pointer.*/
    if (a !=NULL && *a != NULL) {
        free(*a);
        *a = NULL;
    }
}
int main()
{
    char* myString = new char[12]{ "hello world" };
    char* myString2 = new char[14]{ "hello world 2" };
    myPrintString(myString, false);
    /* Free the string.*/
    myFreeString(myString);
    /* myString is freed, and myString is not null.*/
    myPrintString(myString,true);
    // Repeat with Function that works.
    myPrintString(myString2, false);
    myFreeString2(&myString2);
    myPrintString(myString2,true);
    return 0;
}
```

**Comment by nhurde** [comment]
I see, will make those updates and apply it to master soon.
